(cl:in-package papillarray_ros_v2-msg)
(cl:export '(HEADER-VAL
          HEADER
          TUS-VAL
          TUS
          PILLARS-VAL
          PILLARS
          GFX-VAL
          GFX
          GFY-VAL
          GFY
          GFZ-VAL
          GFZ
          GTX-VAL
          GTX
          GTY-VAL
          GTY
          GTZ-VAL
          GTZ
          FRICTION_EST-VAL
          FRICTION_EST
          TARGET_GRIP_FORCE-VAL
          TARGET_GRIP_FORCE
          IS_SD_ACTIVE-VAL
          IS_SD_ACTIVE
          IS_REF_LOADED-VAL
          IS_REF_LOADED
          IS_CONTACT-VAL
          IS_CONTACT
))