(cl:defpackage papillarray_ros_v2-srv
  (:use )
  (:export
   "BIASREQUEST"
   "<BIASREQUEST-REQUEST>"
   "BIASREQUEST-REQUEST"
   "<BIASREQUEST-RESPONSE>"
   "BIASREQUEST-RESPONSE"
   "STARTSLIPDETECTION"
   "<STARTSLIPDETECTION-REQUEST>"
   "STARTSLIPDETECTION-REQUEST"
   "<STARTSLIPDETECTION-RESPONSE>"
   "STARTSLIPDETECTION-RESPONSE"
   "STOPSLIPDETECTION"
   "<STOPSLIPDETECTION-REQUEST>"
   "STOPSLIPDETECTION-REQUEST"
   "<STOPSLIPDETECTION-RESPONSE>"
   "STOPSLIPDETECTION-RESPONSE"
  ))

