// Generated by gencpp from file papillarray_ros_v2/StartSlipDetection.msg
// DO NOT EDIT!


#ifndef PAPILLARRAY_ROS_V2_MESSAGE_STARTSLIPDETECTION_H
#define PAPILLARRAY_ROS_V2_MESSAGE_STARTSLIPDETECTION_H

#include <ros/service_traits.h>


#include <papillarray_ros_v2/StartSlipDetectionRequest.h>
#include <papillarray_ros_v2/StartSlipDetectionResponse.h>


namespace papillarray_ros_v2
{

struct StartSlipDetection
{

typedef StartSlipDetectionRequest Request;
typedef StartSlipDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartSlipDetection
} // namespace papillarray_ros_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::papillarray_ros_v2::StartSlipDetection > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::papillarray_ros_v2::StartSlipDetection&) { return value(); }
};

template<>
struct DataType< ::papillarray_ros_v2::StartSlipDetection > {
  static const char* value()
  {
    return "papillarray_ros_v2/StartSlipDetection";
  }

  static const char* value(const ::papillarray_ros_v2::StartSlipDetection&) { return value(); }
};


// service_traits::MD5Sum< ::papillarray_ros_v2::StartSlipDetectionRequest> should match
// service_traits::MD5Sum< ::papillarray_ros_v2::StartSlipDetection >
template<>
struct MD5Sum< ::papillarray_ros_v2::StartSlipDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::papillarray_ros_v2::StartSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StartSlipDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::papillarray_ros_v2::StartSlipDetectionRequest> should match
// service_traits::DataType< ::papillarray_ros_v2::StartSlipDetection >
template<>
struct DataType< ::papillarray_ros_v2::StartSlipDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::papillarray_ros_v2::StartSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StartSlipDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::papillarray_ros_v2::StartSlipDetectionResponse> should match
// service_traits::MD5Sum< ::papillarray_ros_v2::StartSlipDetection >
template<>
struct MD5Sum< ::papillarray_ros_v2::StartSlipDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::papillarray_ros_v2::StartSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StartSlipDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::papillarray_ros_v2::StartSlipDetectionResponse> should match
// service_traits::DataType< ::papillarray_ros_v2::StartSlipDetection >
template<>
struct DataType< ::papillarray_ros_v2::StartSlipDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::papillarray_ros_v2::StartSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StartSlipDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAPILLARRAY_ROS_V2_MESSAGE_STARTSLIPDETECTION_H
