// Generated by gencpp from file papillarray_ros_v2/StopSlipDetection.msg
// DO NOT EDIT!


#ifndef PAPILLARRAY_ROS_V2_MESSAGE_STOPSLIPDETECTION_H
#define PAPILLARRAY_ROS_V2_MESSAGE_STOPSLIPDETECTION_H

#include <ros/service_traits.h>


#include <papillarray_ros_v2/StopSlipDetectionRequest.h>
#include <papillarray_ros_v2/StopSlipDetectionResponse.h>


namespace papillarray_ros_v2
{

struct StopSlipDetection
{

typedef StopSlipDetectionRequest Request;
typedef StopSlipDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopSlipDetection
} // namespace papillarray_ros_v2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::papillarray_ros_v2::StopSlipDetection > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::papillarray_ros_v2::StopSlipDetection&) { return value(); }
};

template<>
struct DataType< ::papillarray_ros_v2::StopSlipDetection > {
  static const char* value()
  {
    return "papillarray_ros_v2/StopSlipDetection";
  }

  static const char* value(const ::papillarray_ros_v2::StopSlipDetection&) { return value(); }
};


// service_traits::MD5Sum< ::papillarray_ros_v2::StopSlipDetectionRequest> should match
// service_traits::MD5Sum< ::papillarray_ros_v2::StopSlipDetection >
template<>
struct MD5Sum< ::papillarray_ros_v2::StopSlipDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::papillarray_ros_v2::StopSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StopSlipDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::papillarray_ros_v2::StopSlipDetectionRequest> should match
// service_traits::DataType< ::papillarray_ros_v2::StopSlipDetection >
template<>
struct DataType< ::papillarray_ros_v2::StopSlipDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::papillarray_ros_v2::StopSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StopSlipDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::papillarray_ros_v2::StopSlipDetectionResponse> should match
// service_traits::MD5Sum< ::papillarray_ros_v2::StopSlipDetection >
template<>
struct MD5Sum< ::papillarray_ros_v2::StopSlipDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::papillarray_ros_v2::StopSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StopSlipDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::papillarray_ros_v2::StopSlipDetectionResponse> should match
// service_traits::DataType< ::papillarray_ros_v2::StopSlipDetection >
template<>
struct DataType< ::papillarray_ros_v2::StopSlipDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::papillarray_ros_v2::StopSlipDetection >::value();
  }
  static const char* value(const ::papillarray_ros_v2::StopSlipDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PAPILLARRAY_ROS_V2_MESSAGE_STOPSLIPDETECTION_H
